name: Unit tests
on:
  push:
    branches:[ master ]
  pull_request:
    branches:[ master ]
jobs:
  run_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python3 test/test_my_utils.py