name: Unit tests

on:
  push:
  pull_request:
    branches: [ master ]
jobs:
  run_style_checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: workflows/environment.yml
          init-shell: bash
      - run: pycodestyle $(git ls-files "*.py")
        shell: bash -l {0}

  run_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: workflows/environment.yml
          init-shell: bash
      - run: |
          python3 test/test_my_utils.py
        shell: bash -l {0}