name: Unit tests
on:
  push:
    branches:[ main ]
  pull_request:
    branches:[ main ]
jobs:
  run_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python3 test/test_my_utils.py